// Generated by gencpp from file robot_msgs/ErrorGoal.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ERRORGOAL_H
#define ROBOT_MSGS_MESSAGE_ERRORGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct ErrorGoal_
{
  typedef ErrorGoal_<ContainerAllocator> Type;

  ErrorGoal_()
    : error_activate(false)  {
    }
  ErrorGoal_(const ContainerAllocator& _alloc)
    : error_activate(false)  {
  (void)_alloc;
    }



   typedef uint8_t _error_activate_type;
  _error_activate_type error_activate;





  typedef boost::shared_ptr< ::robot_msgs::ErrorGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::ErrorGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ErrorGoal_

typedef ::robot_msgs::ErrorGoal_<std::allocator<void> > ErrorGoal;

typedef boost::shared_ptr< ::robot_msgs::ErrorGoal > ErrorGoalPtr;
typedef boost::shared_ptr< ::robot_msgs::ErrorGoal const> ErrorGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::ErrorGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::ErrorGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::ErrorGoal_<ContainerAllocator1> & lhs, const ::robot_msgs::ErrorGoal_<ContainerAllocator2> & rhs)
{
  return lhs.error_activate == rhs.error_activate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::ErrorGoal_<ContainerAllocator1> & lhs, const ::robot_msgs::ErrorGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ErrorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ErrorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ErrorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ErrorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ErrorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ErrorGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::ErrorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "337fec9e4b55f05ed4004302c4de9f59";
  }

  static const char* value(const ::robot_msgs::ErrorGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x337fec9e4b55f05eULL;
  static const uint64_t static_value2 = 0xd4004302c4de9f59ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::ErrorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/ErrorGoal";
  }

  static const char* value(const ::robot_msgs::ErrorGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::ErrorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"bool error_activate\n"
;
  }

  static const char* value(const ::robot_msgs::ErrorGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::ErrorGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_activate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ErrorGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::ErrorGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::ErrorGoal_<ContainerAllocator>& v)
  {
    s << indent << "error_activate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_activate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ERRORGOAL_H
