// Generated by gencpp from file robot_msgs/ErrorFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ERRORFEEDBACK_H
#define ROBOT_MSGS_MESSAGE_ERRORFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct ErrorFeedback_
{
  typedef ErrorFeedback_<ContainerAllocator> Type;

  ErrorFeedback_()
    : error_feedback(false)  {
    }
  ErrorFeedback_(const ContainerAllocator& _alloc)
    : error_feedback(false)  {
  (void)_alloc;
    }



   typedef uint8_t _error_feedback_type;
  _error_feedback_type error_feedback;





  typedef boost::shared_ptr< ::robot_msgs::ErrorFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::ErrorFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ErrorFeedback_

typedef ::robot_msgs::ErrorFeedback_<std::allocator<void> > ErrorFeedback;

typedef boost::shared_ptr< ::robot_msgs::ErrorFeedback > ErrorFeedbackPtr;
typedef boost::shared_ptr< ::robot_msgs::ErrorFeedback const> ErrorFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::ErrorFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::ErrorFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::ErrorFeedback_<ContainerAllocator1> & lhs, const ::robot_msgs::ErrorFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.error_feedback == rhs.error_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::ErrorFeedback_<ContainerAllocator1> & lhs, const ::robot_msgs::ErrorFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ErrorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ErrorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ErrorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ErrorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ErrorFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ErrorFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::ErrorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96cc3af87c8ab60608117ee1f72cc4fc";
  }

  static const char* value(const ::robot_msgs::ErrorFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96cc3af87c8ab606ULL;
  static const uint64_t static_value2 = 0x08117ee1f72cc4fcULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::ErrorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/ErrorFeedback";
  }

  static const char* value(const ::robot_msgs::ErrorFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::ErrorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"bool error_feedback\n"
"\n"
"\n"
;
  }

  static const char* value(const ::robot_msgs::ErrorFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::ErrorFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ErrorFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::ErrorFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::ErrorFeedback_<ContainerAllocator>& v)
  {
    s << indent << "error_feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ERRORFEEDBACK_H
