// Generated by gencpp from file robot_msgs/Location.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_LOCATION_H
#define ROBOT_MSGS_MESSAGE_LOCATION_H

#include <ros/service_traits.h>


#include <robot_msgs/LocationRequest.h>
#include <robot_msgs/LocationResponse.h>


namespace robot_msgs
{

struct Location
{

typedef LocationRequest Request;
typedef LocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Location
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::Location > {
  static const char* value()
  {
    return "7e5777edad1b26d8d53bfb68b780c64f";
  }

  static const char* value(const ::robot_msgs::Location&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::Location > {
  static const char* value()
  {
    return "robot_msgs/Location";
  }

  static const char* value(const ::robot_msgs::Location&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::LocationRequest> should match
// service_traits::MD5Sum< ::robot_msgs::Location >
template<>
struct MD5Sum< ::robot_msgs::LocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Location >::value();
  }
  static const char* value(const ::robot_msgs::LocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::LocationRequest> should match
// service_traits::DataType< ::robot_msgs::Location >
template<>
struct DataType< ::robot_msgs::LocationRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Location >::value();
  }
  static const char* value(const ::robot_msgs::LocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::LocationResponse> should match
// service_traits::MD5Sum< ::robot_msgs::Location >
template<>
struct MD5Sum< ::robot_msgs::LocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Location >::value();
  }
  static const char* value(const ::robot_msgs::LocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::LocationResponse> should match
// service_traits::DataType< ::robot_msgs::Location >
template<>
struct DataType< ::robot_msgs::LocationResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Location >::value();
  }
  static const char* value(const ::robot_msgs::LocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_LOCATION_H
