// Generated by gencpp from file robot_msgs/MissionFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MISSIONFEEDBACK_H
#define ROBOT_MSGS_MESSAGE_MISSIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_msgs/Feedback.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct MissionFeedback_
{
  typedef MissionFeedback_<ContainerAllocator> Type;

  MissionFeedback_()
    : mission_feedback()  {
    }
  MissionFeedback_(const ContainerAllocator& _alloc)
    : mission_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robot_msgs::Feedback_<ContainerAllocator>  _mission_feedback_type;
  _mission_feedback_type mission_feedback;





  typedef boost::shared_ptr< ::robot_msgs::MissionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::MissionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MissionFeedback_

typedef ::robot_msgs::MissionFeedback_<std::allocator<void> > MissionFeedback;

typedef boost::shared_ptr< ::robot_msgs::MissionFeedback > MissionFeedbackPtr;
typedef boost::shared_ptr< ::robot_msgs::MissionFeedback const> MissionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::MissionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::MissionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::MissionFeedback_<ContainerAllocator1> & lhs, const ::robot_msgs::MissionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.mission_feedback == rhs.mission_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::MissionFeedback_<ContainerAllocator1> & lhs, const ::robot_msgs::MissionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MissionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MissionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MissionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MissionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MissionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MissionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::MissionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dede4bc6b199919896f29013dbd6378";
  }

  static const char* value(const ::robot_msgs::MissionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dede4bc6b199919ULL;
  static const uint64_t static_value2 = 0x896f29013dbd6378ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::MissionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/MissionFeedback";
  }

  static const char* value(const ::robot_msgs::MissionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::MissionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"robot_msgs/Feedback mission_feedback\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_msgs/Feedback\n"
"#mission status\n"
"int32 IDLE =0\n"
"int32 ACTIVE =1\n"
"int32 SUCCESS =2\n"
"int32 ABORTED =3\n"
"int32 PAUSED =4\n"
"\n"
"\n"
"string index\n"
"string mission_id\n"
"int16 number\n"
"int16 status\n"
"float32 completion_percentage\n"
"int32 time_elapsed\n"
"int32 priority_level\n"
;
  }

  static const char* value(const ::robot_msgs::MissionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::MissionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::MissionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::MissionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "mission_feedback: ";
    s << std::endl;
    Printer< ::robot_msgs::Feedback_<ContainerAllocator> >::stream(s, indent + "  ", v.mission_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MISSIONFEEDBACK_H
