// Generated by gencpp from file robot_msgs/MoveGoal.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MOVEGOAL_H
#define ROBOT_MSGS_MESSAGE_MOVEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct MoveGoal_
{
  typedef MoveGoal_<ContainerAllocator> Type;

  MoveGoal_()
    : source_id(0)
    , target_id(0)  {
    }
  MoveGoal_(const ContainerAllocator& _alloc)
    : source_id(0)
    , target_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _source_id_type;
  _source_id_type source_id;

   typedef int32_t _target_id_type;
  _target_id_type target_id;





  typedef boost::shared_ptr< ::robot_msgs::MoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::MoveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveGoal_

typedef ::robot_msgs::MoveGoal_<std::allocator<void> > MoveGoal;

typedef boost::shared_ptr< ::robot_msgs::MoveGoal > MoveGoalPtr;
typedef boost::shared_ptr< ::robot_msgs::MoveGoal const> MoveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::MoveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::MoveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::MoveGoal_<ContainerAllocator1> & lhs, const ::robot_msgs::MoveGoal_<ContainerAllocator2> & rhs)
{
  return lhs.source_id == rhs.source_id &&
    lhs.target_id == rhs.target_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::MoveGoal_<ContainerAllocator1> & lhs, const ::robot_msgs::MoveGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MoveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::MoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "066e25a6a7f28470cd61883729c7a899";
  }

  static const char* value(const ::robot_msgs::MoveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x066e25a6a7f28470ULL;
  static const uint64_t static_value2 = 0xcd61883729c7a899ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::MoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/MoveGoal";
  }

  static const char* value(const ::robot_msgs::MoveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::MoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 source_id\n"
"int32 target_id\n"
;
  }

  static const char* value(const ::robot_msgs::MoveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::MoveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source_id);
      stream.next(m.target_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::MoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::MoveGoal_<ContainerAllocator>& v)
  {
    s << indent << "source_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.source_id);
    s << indent << "target_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MOVEGOAL_H
