// Generated by gencpp from file robot_msgs/MoveFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MOVEFEEDBACK_H
#define ROBOT_MSGS_MESSAGE_MOVEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct MoveFeedback_
{
  typedef MoveFeedback_<ContainerAllocator> Type;

  MoveFeedback_()
    : move_feedback(false)  {
    }
  MoveFeedback_(const ContainerAllocator& _alloc)
    : move_feedback(false)  {
  (void)_alloc;
    }



   typedef uint8_t _move_feedback_type;
  _move_feedback_type move_feedback;





  typedef boost::shared_ptr< ::robot_msgs::MoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::MoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveFeedback_

typedef ::robot_msgs::MoveFeedback_<std::allocator<void> > MoveFeedback;

typedef boost::shared_ptr< ::robot_msgs::MoveFeedback > MoveFeedbackPtr;
typedef boost::shared_ptr< ::robot_msgs::MoveFeedback const> MoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::MoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::MoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::MoveFeedback_<ContainerAllocator1> & lhs, const ::robot_msgs::MoveFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.move_feedback == rhs.move_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::MoveFeedback_<ContainerAllocator1> & lhs, const ::robot_msgs::MoveFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69e867d33e8cc74193e08d830707425b";
  }

  static const char* value(const ::robot_msgs::MoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69e867d33e8cc741ULL;
  static const uint64_t static_value2 = 0x93e08d830707425bULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/MoveFeedback";
  }

  static const char* value(const ::robot_msgs::MoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"bool move_feedback\n"
"\n"
;
  }

  static const char* value(const ::robot_msgs::MoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::MoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.move_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::MoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::MoveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "move_feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.move_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MOVEFEEDBACK_H
