// Generated by gencpp from file robot_msgs/Task.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_TASK_H
#define ROBOT_MSGS_MESSAGE_TASK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct Task_
{
  typedef Task_<ContainerAllocator> Type;

  Task_()
    : index()
    , coordinate_index()
    , waypoint_index(0)
    , map_name()
    , coordinate()
    , number(0)
    , activate(false)  {
    }
  Task_(const ContainerAllocator& _alloc)
    : index(_alloc)
    , coordinate_index(_alloc)
    , waypoint_index(0)
    , map_name(_alloc)
    , coordinate(_alloc)
    , number(0)
    , activate(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _index_type;
  _index_type index;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _coordinate_index_type;
  _coordinate_index_type coordinate_index;

   typedef int16_t _waypoint_index_type;
  _waypoint_index_type waypoint_index;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_name_type;
  _map_name_type map_name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _coordinate_type;
  _coordinate_type coordinate;

   typedef int16_t _number_type;
  _number_type number;

   typedef uint8_t _activate_type;
  _activate_type activate;





  typedef boost::shared_ptr< ::robot_msgs::Task_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::Task_<ContainerAllocator> const> ConstPtr;

}; // struct Task_

typedef ::robot_msgs::Task_<std::allocator<void> > Task;

typedef boost::shared_ptr< ::robot_msgs::Task > TaskPtr;
typedef boost::shared_ptr< ::robot_msgs::Task const> TaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::Task_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::Task_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::Task_<ContainerAllocator1> & lhs, const ::robot_msgs::Task_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.coordinate_index == rhs.coordinate_index &&
    lhs.waypoint_index == rhs.waypoint_index &&
    lhs.map_name == rhs.map_name &&
    lhs.coordinate == rhs.coordinate &&
    lhs.number == rhs.number &&
    lhs.activate == rhs.activate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::Task_<ContainerAllocator1> & lhs, const ::robot_msgs::Task_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Task_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Task_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Task_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Task_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::Task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b471fe2edd3aa8f13fe189d792d154a";
  }

  static const char* value(const ::robot_msgs::Task_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b471fe2edd3aa8fULL;
  static const uint64_t static_value2 = 0x13fe189d792d154aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::Task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/Task";
  }

  static const char* value(const ::robot_msgs::Task_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::Task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string index\n"
"string coordinate_index\n"
"int16 waypoint_index\n"
"string map_name\n"
"geometry_msgs/Pose coordinate\n"
"int16 number\n"
"bool activate\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robot_msgs::Task_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::Task_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.coordinate_index);
      stream.next(m.waypoint_index);
      stream.next(m.map_name);
      stream.next(m.coordinate);
      stream.next(m.number);
      stream.next(m.activate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Task_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::Task_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::Task_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.index);
    s << indent << "coordinate_index: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.coordinate_index);
    s << indent << "waypoint_index: ";
    Printer<int16_t>::stream(s, indent + "  ", v.waypoint_index);
    s << indent << "map_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_name);
    s << indent << "coordinate: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.coordinate);
    s << indent << "number: ";
    Printer<int16_t>::stream(s, indent + "  ", v.number);
    s << indent << "activate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.activate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_TASK_H
