// Generated by gencpp from file robot_msgs/UserFeedbackRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_USERFEEDBACKREQUEST_H
#define ROBOT_MSGS_MESSAGE_USERFEEDBACKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct UserFeedbackRequest_
{
  typedef UserFeedbackRequest_<ContainerAllocator> Type;

  UserFeedbackRequest_()
    : user_feedback(false)  {
    }
  UserFeedbackRequest_(const ContainerAllocator& _alloc)
    : user_feedback(false)  {
  (void)_alloc;
    }



   typedef uint8_t _user_feedback_type;
  _user_feedback_type user_feedback;





  typedef boost::shared_ptr< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UserFeedbackRequest_

typedef ::robot_msgs::UserFeedbackRequest_<std::allocator<void> > UserFeedbackRequest;

typedef boost::shared_ptr< ::robot_msgs::UserFeedbackRequest > UserFeedbackRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::UserFeedbackRequest const> UserFeedbackRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::UserFeedbackRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::UserFeedbackRequest_<ContainerAllocator2> & rhs)
{
  return lhs.user_feedback == rhs.user_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::UserFeedbackRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::UserFeedbackRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e38d52427a1bbf9fb49f84c566a793d8";
  }

  static const char* value(const ::robot_msgs::UserFeedbackRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe38d52427a1bbf9fULL;
  static const uint64_t static_value2 = 0xb49f84c566a793d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/UserFeedbackRequest";
  }

  static const char* value(const ::robot_msgs::UserFeedbackRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool user_feedback\n"
;
  }

  static const char* value(const ::robot_msgs::UserFeedbackRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UserFeedbackRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::UserFeedbackRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::UserFeedbackRequest_<ContainerAllocator>& v)
  {
    s << indent << "user_feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.user_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_USERFEEDBACKREQUEST_H
