// Generated by gencpp from file robot_msgs/WaitGoal.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_WAITGOAL_H
#define ROBOT_MSGS_MESSAGE_WAITGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct WaitGoal_
{
  typedef WaitGoal_<ContainerAllocator> Type;

  WaitGoal_()
    : wait_time(0)
    , wait_activate(false)  {
    }
  WaitGoal_(const ContainerAllocator& _alloc)
    : wait_time(0)
    , wait_activate(false)  {
  (void)_alloc;
    }



   typedef int16_t _wait_time_type;
  _wait_time_type wait_time;

   typedef uint8_t _wait_activate_type;
  _wait_activate_type wait_activate;





  typedef boost::shared_ptr< ::robot_msgs::WaitGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::WaitGoal_<ContainerAllocator> const> ConstPtr;

}; // struct WaitGoal_

typedef ::robot_msgs::WaitGoal_<std::allocator<void> > WaitGoal;

typedef boost::shared_ptr< ::robot_msgs::WaitGoal > WaitGoalPtr;
typedef boost::shared_ptr< ::robot_msgs::WaitGoal const> WaitGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::WaitGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::WaitGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::WaitGoal_<ContainerAllocator1> & lhs, const ::robot_msgs::WaitGoal_<ContainerAllocator2> & rhs)
{
  return lhs.wait_time == rhs.wait_time &&
    lhs.wait_activate == rhs.wait_activate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::WaitGoal_<ContainerAllocator1> & lhs, const ::robot_msgs::WaitGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::WaitGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::WaitGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::WaitGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::WaitGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::WaitGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::WaitGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::WaitGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bab51433acee64a29a6408e5a7db413";
  }

  static const char* value(const ::robot_msgs::WaitGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bab51433acee64aULL;
  static const uint64_t static_value2 = 0x29a6408e5a7db413ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::WaitGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/WaitGoal";
  }

  static const char* value(const ::robot_msgs::WaitGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::WaitGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int16 wait_time\n"
"bool wait_activate\n"
;
  }

  static const char* value(const ::robot_msgs::WaitGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::WaitGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wait_time);
      stream.next(m.wait_activate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaitGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::WaitGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::WaitGoal_<ContainerAllocator>& v)
  {
    s << indent << "wait_time: ";
    Printer<int16_t>::stream(s, indent + "  ", v.wait_time);
    s << indent << "wait_activate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wait_activate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_WAITGOAL_H
