// Auto-generated. Do not edit!

// (in-package robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class WaitGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.wait_time = null;
      this.wait_activate = null;
    }
    else {
      if (initObj.hasOwnProperty('wait_time')) {
        this.wait_time = initObj.wait_time
      }
      else {
        this.wait_time = 0;
      }
      if (initObj.hasOwnProperty('wait_activate')) {
        this.wait_activate = initObj.wait_activate
      }
      else {
        this.wait_activate = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type WaitGoal
    // Serialize message field [wait_time]
    bufferOffset = _serializer.int16(obj.wait_time, buffer, bufferOffset);
    // Serialize message field [wait_activate]
    bufferOffset = _serializer.bool(obj.wait_activate, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type WaitGoal
    let len;
    let data = new WaitGoal(null);
    // Deserialize message field [wait_time]
    data.wait_time = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [wait_activate]
    data.wait_activate = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 3;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_msgs/WaitGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9bab51433acee64a29a6408e5a7db413';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    int16 wait_time
    bool wait_activate
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new WaitGoal(null);
    if (msg.wait_time !== undefined) {
      resolved.wait_time = msg.wait_time;
    }
    else {
      resolved.wait_time = 0
    }

    if (msg.wait_activate !== undefined) {
      resolved.wait_activate = msg.wait_activate;
    }
    else {
      resolved.wait_activate = false
    }

    return resolved;
    }
};

module.exports = WaitGoal;
