# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_msgs/Task.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Task(genpy.Message):
  _md5sum = "6b471fe2edd3aa8f13fe189d792d154a"
  _type = "robot_msgs/Task"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string index
string coordinate_index
int16 waypoint_index
string map_name
geometry_msgs/Pose coordinate
int16 number
bool activate


================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['index','coordinate_index','waypoint_index','map_name','coordinate','number','activate']
  _slot_types = ['string','string','int16','string','geometry_msgs/Pose','int16','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       index,coordinate_index,waypoint_index,map_name,coordinate,number,activate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Task, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.index is None:
        self.index = ''
      if self.coordinate_index is None:
        self.coordinate_index = ''
      if self.waypoint_index is None:
        self.waypoint_index = 0
      if self.map_name is None:
        self.map_name = ''
      if self.coordinate is None:
        self.coordinate = geometry_msgs.msg.Pose()
      if self.number is None:
        self.number = 0
      if self.activate is None:
        self.activate = False
    else:
      self.index = ''
      self.coordinate_index = ''
      self.waypoint_index = 0
      self.map_name = ''
      self.coordinate = geometry_msgs.msg.Pose()
      self.number = 0
      self.activate = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.index
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.coordinate_index
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.waypoint_index
      buff.write(_get_struct_h().pack(_x))
      _x = self.map_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7dhB().pack(_x.coordinate.position.x, _x.coordinate.position.y, _x.coordinate.position.z, _x.coordinate.orientation.x, _x.coordinate.orientation.y, _x.coordinate.orientation.z, _x.coordinate.orientation.w, _x.number, _x.activate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.coordinate is None:
        self.coordinate = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.index = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.index = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.coordinate_index = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.coordinate_index = str[start:end]
      start = end
      end += 2
      (self.waypoint_index,) = _get_struct_h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.map_name = str[start:end]
      _x = self
      start = end
      end += 59
      (_x.coordinate.position.x, _x.coordinate.position.y, _x.coordinate.position.z, _x.coordinate.orientation.x, _x.coordinate.orientation.y, _x.coordinate.orientation.z, _x.coordinate.orientation.w, _x.number, _x.activate,) = _get_struct_7dhB().unpack(str[start:end])
      self.activate = bool(self.activate)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.index
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.coordinate_index
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.waypoint_index
      buff.write(_get_struct_h().pack(_x))
      _x = self.map_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7dhB().pack(_x.coordinate.position.x, _x.coordinate.position.y, _x.coordinate.position.z, _x.coordinate.orientation.x, _x.coordinate.orientation.y, _x.coordinate.orientation.z, _x.coordinate.orientation.w, _x.number, _x.activate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.coordinate is None:
        self.coordinate = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.index = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.index = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.coordinate_index = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.coordinate_index = str[start:end]
      start = end
      end += 2
      (self.waypoint_index,) = _get_struct_h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.map_name = str[start:end]
      _x = self
      start = end
      end += 59
      (_x.coordinate.position.x, _x.coordinate.position.y, _x.coordinate.position.z, _x.coordinate.orientation.x, _x.coordinate.orientation.y, _x.coordinate.orientation.z, _x.coordinate.orientation.w, _x.number, _x.activate,) = _get_struct_7dhB().unpack(str[start:end])
      self.activate = bool(self.activate)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7dhB = None
def _get_struct_7dhB():
    global _struct_7dhB
    if _struct_7dhB is None:
        _struct_7dhB = struct.Struct("<7dhB")
    return _struct_7dhB
_struct_h = None
def _get_struct_h():
    global _struct_h
    if _struct_h is None:
        _struct_h = struct.Struct("<h")
    return _struct_h
