; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude ErrorGoal.msg.html

(cl:defclass <ErrorGoal> (roslisp-msg-protocol:ros-message)
  ((error_activate
    :reader error_activate
    :initarg :error_activate
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ErrorGoal (<ErrorGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ErrorGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ErrorGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<ErrorGoal> is deprecated: use robot_msgs-msg:ErrorGoal instead.")))

(cl:ensure-generic-function 'error_activate-val :lambda-list '(m))
(cl:defmethod error_activate-val ((m <ErrorGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:error_activate-val is deprecated.  Use robot_msgs-msg:error_activate instead.")
  (error_activate m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ErrorGoal>) ostream)
  "Serializes a message object of type '<ErrorGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'error_activate) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ErrorGoal>) istream)
  "Deserializes a message object of type '<ErrorGoal>"
    (cl:setf (cl:slot-value msg 'error_activate) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ErrorGoal>)))
  "Returns string type for a message object of type '<ErrorGoal>"
  "robot_msgs/ErrorGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ErrorGoal)))
  "Returns string type for a message object of type 'ErrorGoal"
  "robot_msgs/ErrorGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ErrorGoal>)))
  "Returns md5sum for a message object of type '<ErrorGoal>"
  "337fec9e4b55f05ed4004302c4de9f59")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ErrorGoal)))
  "Returns md5sum for a message object of type 'ErrorGoal"
  "337fec9e4b55f05ed4004302c4de9f59")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ErrorGoal>)))
  "Returns full string definition for message of type '<ErrorGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool error_activate~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ErrorGoal)))
  "Returns full string definition for message of type 'ErrorGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool error_activate~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ErrorGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ErrorGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ErrorGoal
    (cl:cons ':error_activate (error_activate msg))
))
