; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude ErrorFeedback.msg.html

(cl:defclass <ErrorFeedback> (roslisp-msg-protocol:ros-message)
  ((error_feedback
    :reader error_feedback
    :initarg :error_feedback
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ErrorFeedback (<ErrorFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ErrorFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ErrorFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<ErrorFeedback> is deprecated: use robot_msgs-msg:ErrorFeedback instead.")))

(cl:ensure-generic-function 'error_feedback-val :lambda-list '(m))
(cl:defmethod error_feedback-val ((m <ErrorFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:error_feedback-val is deprecated.  Use robot_msgs-msg:error_feedback instead.")
  (error_feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ErrorFeedback>) ostream)
  "Serializes a message object of type '<ErrorFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'error_feedback) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ErrorFeedback>) istream)
  "Deserializes a message object of type '<ErrorFeedback>"
    (cl:setf (cl:slot-value msg 'error_feedback) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ErrorFeedback>)))
  "Returns string type for a message object of type '<ErrorFeedback>"
  "robot_msgs/ErrorFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ErrorFeedback)))
  "Returns string type for a message object of type 'ErrorFeedback"
  "robot_msgs/ErrorFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ErrorFeedback>)))
  "Returns md5sum for a message object of type '<ErrorFeedback>"
  "96cc3af87c8ab60608117ee1f72cc4fc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ErrorFeedback)))
  "Returns md5sum for a message object of type 'ErrorFeedback"
  "96cc3af87c8ab60608117ee1f72cc4fc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ErrorFeedback>)))
  "Returns full string definition for message of type '<ErrorFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool error_feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ErrorFeedback)))
  "Returns full string definition for message of type 'ErrorFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool error_feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ErrorFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ErrorFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ErrorFeedback
    (cl:cons ':error_feedback (error_feedback msg))
))
