; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude ErrorResult.msg.html

(cl:defclass <ErrorResult> (roslisp-msg-protocol:ros-message)
  ((is_success
    :reader is_success
    :initarg :is_success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ErrorResult (<ErrorResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ErrorResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ErrorResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<ErrorResult> is deprecated: use robot_msgs-msg:ErrorResult instead.")))

(cl:ensure-generic-function 'is_success-val :lambda-list '(m))
(cl:defmethod is_success-val ((m <ErrorResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:is_success-val is deprecated.  Use robot_msgs-msg:is_success instead.")
  (is_success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ErrorResult>) ostream)
  "Serializes a message object of type '<ErrorResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ErrorResult>) istream)
  "Deserializes a message object of type '<ErrorResult>"
    (cl:setf (cl:slot-value msg 'is_success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ErrorResult>)))
  "Returns string type for a message object of type '<ErrorResult>"
  "robot_msgs/ErrorResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ErrorResult)))
  "Returns string type for a message object of type 'ErrorResult"
  "robot_msgs/ErrorResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ErrorResult>)))
  "Returns md5sum for a message object of type '<ErrorResult>"
  "fa3e942e5cfe76a6a46f20a0780b2cf3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ErrorResult)))
  "Returns md5sum for a message object of type 'ErrorResult"
  "fa3e942e5cfe76a6a46f20a0780b2cf3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ErrorResult>)))
  "Returns full string definition for message of type '<ErrorResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool is_success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ErrorResult)))
  "Returns full string definition for message of type 'ErrorResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool is_success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ErrorResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ErrorResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ErrorResult
    (cl:cons ':is_success (is_success msg))
))
