; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude WaitGoal.msg.html

(cl:defclass <WaitGoal> (roslisp-msg-protocol:ros-message)
  ((wait_time
    :reader wait_time
    :initarg :wait_time
    :type cl:fixnum
    :initform 0)
   (wait_activate
    :reader wait_activate
    :initarg :wait_activate
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass WaitGoal (<WaitGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WaitGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WaitGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<WaitGoal> is deprecated: use robot_msgs-msg:WaitGoal instead.")))

(cl:ensure-generic-function 'wait_time-val :lambda-list '(m))
(cl:defmethod wait_time-val ((m <WaitGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:wait_time-val is deprecated.  Use robot_msgs-msg:wait_time instead.")
  (wait_time m))

(cl:ensure-generic-function 'wait_activate-val :lambda-list '(m))
(cl:defmethod wait_activate-val ((m <WaitGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:wait_activate-val is deprecated.  Use robot_msgs-msg:wait_activate instead.")
  (wait_activate m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WaitGoal>) ostream)
  "Serializes a message object of type '<WaitGoal>"
  (cl:let* ((signed (cl:slot-value msg 'wait_time)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'wait_activate) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WaitGoal>) istream)
  "Deserializes a message object of type '<WaitGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'wait_time) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
    (cl:setf (cl:slot-value msg 'wait_activate) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WaitGoal>)))
  "Returns string type for a message object of type '<WaitGoal>"
  "robot_msgs/WaitGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WaitGoal)))
  "Returns string type for a message object of type 'WaitGoal"
  "robot_msgs/WaitGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WaitGoal>)))
  "Returns md5sum for a message object of type '<WaitGoal>"
  "9bab51433acee64a29a6408e5a7db413")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WaitGoal)))
  "Returns md5sum for a message object of type 'WaitGoal"
  "9bab51433acee64a29a6408e5a7db413")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WaitGoal>)))
  "Returns full string definition for message of type '<WaitGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int16 wait_time~%bool wait_activate~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WaitGoal)))
  "Returns full string definition for message of type 'WaitGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int16 wait_time~%bool wait_activate~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WaitGoal>))
  (cl:+ 0
     2
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WaitGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'WaitGoal
    (cl:cons ':wait_time (wait_time msg))
    (cl:cons ':wait_activate (wait_activate msg))
))
