(cl:defpackage robot_msgs-srv
  (:use )
  (:export
   "LOCATION"
   "<LOCATION-REQUEST>"
   "LOCATION-REQUEST"
   "<LOCATION-RESPONSE>"
   "LOCATION-RESPONSE"
   "USERFEEDBACK"
   "<USERFEEDBACK-REQUEST>"
   "USERFEEDBACK-REQUEST"
   "<USERFEEDBACK-RESPONSE>"
   "USERFEEDBACK-RESPONSE"
  ))

